name: compliancenavigator
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.9.0
  get: ^4.7.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  dropdown_button2: ^2.3.9
  webview_flutter: ^4.10.0
  dio: ^5.4.0
  connectivity_plus: ^6.1.4
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^23.1.40
  syncfusion_flutter_core: ^23.1.40
  photo_view: ^0.15.0
  # syncfusion_flutter_pdfviewer: ^23.2.7
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-01_(2).png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/jsons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
